apiVersion: types.kubefed.io/v1beta1
kind: FederatedSecret
metadata:
  name: mysecret
spec:
  placement:
    clusterSelector:
      matchLabels: {}
  overrides:
    - clusterName: cluster1
      clusterOverrides:
        - path: "/data/username"
          value: "bXlDbHVzdGVyMVVzZXI="
    - clusterName: cluster4
      clusterOverrides:
        - path: "/data/username"
          value: "bXlDbHVzdGVyNFVzZXI="
  template:
    data:
      password: MWYyZDFlMmU2N2Rm
      username: YWRtaW4=
    type: Opaque
