apiVersion: types.kubefed.io/v1beta1
kind: FederatedSecret
metadata:
  name: mysecret
spec:
  placement:
    clusterSelector:
      matchExpressions:
      - {key: provider, operator: NotIn, values: [gcp]}
  template:
    data:
      password: MWYyZDFlMmU2N2Rm
      username: YWRtaW4=
    type: Opaque
